[profile.dev]
opt-level = 0
debug = true
strip = "none"
debug-assertions = true
incremental = true

[profile.release-with-debug]
inherits = "release"
debug = true

[workspace]
members = ["wgui", "wgui/uidev-vk", "wlx-overlay-s", "wlx-capture"]
resolver = "3"

[workspace.dependencies]
anyhow = "1.0.98"
glam = "0.30.3"
log = "0.4.27"
vulkano = { version = "0.35.1", default-features = false, features = [
  "macros",
] }
vulkano-shaders = "0.35.0"
wayland-client = { version = "0.31.10" }
